name: Check SUSFS Module Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 12:00 PM VN

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest
        run: git pull origin main || true

      - name: Get Release
        id: info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          JSON=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/sidex15/susfs4ksu-module/releases/latest)
          TAG=$(echo "$JSON" | jq -r '.tag_name // empty')
          ASSET=$(echo "$JSON" | jq -r '.assets[] | select(.name | endswith(".zip"))' | head -n 1)
          FILE_NAME=$(echo "$ASSET" | jq -r '.name // empty')
          DL_URL=$(echo "$ASSET" | jq -r '.browser_download_url // empty')
          SIZE=$(echo "$ASSET" | jq -r '.size // 0')
          DATE=$(echo "$JSON" | jq -r '.published_at // empty')

          if [ -z "$FILE_NAME" ] || [ "$FILE_NAME" = "null" ]; then
            FILE_NAME="susfs4ksu-${TAG}.zip"
            DL_URL="https://github.com/sidex15/susfs4ksu-module/archive/refs/tags/${TAG}.zip"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          echo "dl_url=$DL_URL" >> $GITHUB_OUTPUT
          echo "size=$SIZE" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Check State
        id: check
        run: |
          touch susfs_state.txt
          if [ "${{ steps.info.outputs.tag }}" = "$(cat susfs_state.txt)" ]; then echo "skip=true" >> $GITHUB_OUTPUT; fi

      - name: Download
        if: steps.check.outputs.skip != 'true'
        run: curl -L -o "${{ steps.info.outputs.file_name }}" "${{ steps.info.outputs.dl_url }}"

      - name: Telegram
        if: steps.check.outputs.skip != 'true'
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        shell: python
        run: |
          import os, requests, datetime
          def get_size(b):
              for unit in ['B','KB','MB']:
                  if b < 1024: return f"{b:.2f} {unit}"
                  b /= 1024
          tag, file_name = "${{ steps.info.outputs.tag }}", "${{ steps.info.outputs.file_name }}"
          size = get_size(int("${{ steps.info.outputs.size }}"))
          date_obj = datetime.datetime.strptime("${{ steps.info.outputs.date }}", "%Y-%m-%dT%H:%M:%SZ") + datetime.timedelta(hours=7)
          caption = f"<b>🚀 SUSFS Module Update!</b>\n\
